name       : ncftp
version    : 3.2.6
release    : 3
source     :
    - ftp://ftp.ncftp.com/ncftp/ncftp-3.2.6-src.tar.xz : 5f200687c05d0807690d9fb770327b226f02dd86155b49e750853fce4e31098d
homepage   : http://ncftp.com
license    : ClArtistic
summary    : full featured command line FTP client
component  : network.clients
rundeps    :
    - ncurses
description: |
    NcFTP is a popular command line alternative to the standard ftp program, containing many ease-of-use and performance enhancements.
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    rm -r %installroot%/usr/etc
