name        : ncftp
version     : 3.2.5
release     : 2
source      :
    - ftp://ftp.ncftp.com/ncftp/ncftp-3.2.5-src.tar.gz : ac111b71112382853b2835c42ebe7bd59acb7f85dd00d44b2c19fbd074a436c4
homepage    : http://ncftp.com
license     : ClArtistic
summary     : full featured command line FTP client
rundeps   :
    - ncurses
description : |
    NcFTP is a popular command line alternative to the standard ftp program, containing many ease-of-use and performance enhancements.
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    rm -r %installroot%/usr/etc
